apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: changeme
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/cb-kubecd/mwm-test-sprign:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
profiles:
- name: dev
  build:
    artifacts:
    - docker: {}
    tagPolicy:
      envTemplate:
        template: '{{.DOCKER_REGISTRY}}/cb-kubecd/mwm-test-sprign:{{.DIGEST_HEX}}'
    local: {}
  deploy:
    helm:
      releases:
      - name: mwm-test-sprign
        chartPath: charts/mwm-test-sprign
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/cb-kubecd/mwm-test-sprign'
          image.tag: '{{.DIGEST_HEX}}'
